version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run:
          name: Check code format
          command: diff -u <(echo -n) <(gofmt -d ./)
      - run:
          name: Build (linux)
          command: |
            make
            tar -c -z -f httpie-go_linux_amd64.tgz ./hg
      - run:
          name: Test
          command: make test
      - run:
          name: Build (mac)
          command: |
            GOOS=darwin make
            tar -c -z -f httpie-go_darwin_amd64.tgz ./hg
      - store_artifacts:
          path: ~/project/httpie-go_linux_amd64.tgz
      - store_artifacts:
          path: ~/project/httpie-go_darwin_amd64.tgz
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
